apiVersion: apps/v1
kind: Deployment
metadata:
  name: bis2bis-app
  labels:
    app: bis2bis-app
spec:
  replicas: 1
  progressDeadlineSeconds: 100
  selector:
    matchLabels:
      app: bis2bis-app
  template:
    metadata:
      labels:
        app: bis2bis-app
    spec:
      containers:
        - name: bis2bis-app
          image: gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
          ports:
          - containerPort: 5000
