apiVersion: "v1"
kind: "Service"
metadata:
  name: "bis2bis-app-service"
  namespace: "default"
  labels:
    app: "bis2bis-app"
spec:
  type: "LoadBalancer"
  selector:
    app: "bis2bis-app"
  ports:
    - protocol: TCP
      port: 5000
